# Generated by Django 5.0.7 on 2024-08-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerDb',
            fields=[
                ('user', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='User Name')),
                ('secret', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
