# Generated by Django 5.0.7 on 2024-08-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdb',
            name='alias',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nama Panggilan'),
        ),
        migrations.AlterField(
            model_name='customerdb',
            name='secret',
            field=models.CharField(max_length=256, verbose_name='Password'),
        ),
    ]
