# Generated by Django 5.0.7 on 2024-08-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_customerdb_alias_alter_customerdb_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdb',
            name='user',
            field=models.SlugField(max_length=256, primary_key=True, serialize=False, verbose_name='User Name'),
        ),
    ]
