# Generated by Django 5.0.7 on 2024-08-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_customerdb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdb',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
