# Generated by Django 5.0.7 on 2024-08-04 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_customerdb_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerBook',
            fields=[
                ('id_book', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('kode_buku', models.CharField(max_length=36)),
                ('last_page', models.PositiveSmallIntegerField(default=0)),
                ('booked_date', models.DateField(blank=True, null=True)),
                ('user_rating', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='landingpage.customerdb')),
            ],
        ),
        migrations.CreateModel(
            name='customerBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('color', models.CharField(choices=[('pink', 'pink'), ('blue', 'blue'), ('red', 'red'), ('yellow', 'yellow'), ('green', 'green'), ('chocolate', 'chocolate'), ('cyan', 'cyan'), ('magenta', 'magenta'), ('purple', 'purple'), ('violet', 'violet'), ('grey', 'grey')], max_length=20)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='landingpage.customerbook')),
            ],
        ),
    ]
