# Generated by Django 5.0.7 on 2024-08-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_customerbook_customerbookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbookmark',
            name='id',
        ),
        migrations.AddField(
            model_name='customerbookmark',
            name='id_bookmark',
            field=models.CharField(default='', max_length=36, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
