# Generated by Django 5.0.7 on 2024-08-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_remove_customerbookmark_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbookmark',
            name='is_penting',
            field=models.BooleanField(default=False),
        ),
    ]
