# Generated by Django 5.0.7 on 2024-08-06 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_remove_customerbook_user_rating_customerbook_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdb',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='customerbook',
            name='point',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerdb',
            name='id',
            field=models.CharField(default=uuid.UUID('f238d849-1239-4ce2-a679-2cd882abd0b3'), max_length=36),
        ),
        migrations.AddField(
            model_name='customerdb',
            name='id_customer',
            field=models.CharField(default='', max_length=50, verbose_name='Data Dari Literatur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdb',
            name='levelling',
            field=models.CharField(choices=[('silver', 'silver'), ('gold', 'gold'), ('platinum', 'platinum')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdb',
            name='total_poin',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
