# Generated by Django 5.0.7 on 2024-08-06 12:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_rename_user_customerdb_user_name_customerbook_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdb',
            name='id',
            field=models.CharField(default=uuid.UUID('c2fd5c6a-c605-4274-85bd-b2c2e1f1cb6b'), max_length=36),
        ),
    ]
