# Generated by Django 5.0.7 on 2024-08-07 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_alter_customerdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdb',
            name='id',
            field=models.CharField(default=uuid.UUID('6d8b9f4c-f570-4a54-b54e-904bf44ffac0'), max_length=36),
        ),
    ]
