# Generated by Django 5.0.7 on 2024-08-08 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0012_alter_customerdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdb',
            name='id',
            field=models.CharField(default=uuid.UUID('8336dccc-7995-4ae5-81e2-05edc1dfa3c0'), max_length=36),
        ),
    ]
