# Generated by Django 5.0.7 on 2024-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_alter_customerdb_options_alter_customerdb_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdb',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='customerdb',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customerdb',
            name='username',
            field=models.SlugField(max_length=256, primary_key=True, serialize=False, verbose_name='User Name'),
        ),
    ]
