# Generated by Django 5.0.7 on 2024-08-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0016_remove_customerdb_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdb',
            name='is_password',
        ),
        migrations.AlterField(
            model_name='customerdb',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
