# Generated by Django 5.0.7 on 2024-08-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0017_remove_customerdb_is_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdb',
            name='secret',
        ),
        migrations.AlterField(
            model_name='customerdb',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
