# Generated by Django 5.1 on 2024-08-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0018_remove_customerdb_secret_alter_customerdb_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbook',
            name='id_book',
            field=models.CharField(blank=True, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbookmark',
            name='id_bookmark',
            field=models.CharField(blank=True, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='customerbookmark',
            unique_together={('id_book', 'page')},
        ),
    ]
