# Generated by Django 5.0.7 on 2024-08-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='point',
            field=models.PositiveIntegerField(default=0, verbose_name='Point'),
        ),
        migrations.AddField(
            model_name='book',
            name='tipe',
            field=models.CharField(choices=[('free', 'free'), ('subscribe', 'subscribe'), ('buy', 'buy')], default='', max_length=20),
        ),
    ]
