# Generated by Django 5.0.7 on 2024-08-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_book_point_book_tipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kategori',
            field=models.CharField(choices=[('PA', 'PA'), ('Pemuridan', 'Pemuridan')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_full',
            field=models.FileField(default='', upload_to='pdf_full', verbose_name='File PDF Full'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_prev',
            field=models.FileField(default='', upload_to='pdf_prev', verbose_name='File PDF Preview'),
            preserve_default=False,
        ),
    ]
