# Generated by Django 5.0.7 on 2024-08-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_book_view_alter_book_id_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_review',
            name='review',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
