# Generated by Django 5.0.7 on 2024-08-10 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0005_book_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_review',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book_review',
            name='updated_review',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
